services:
  stock-api:
    image: stock-manager-api:0.01

    ports:
      - "8080:8080"


    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}